"""Generates a deterministic SQL Server regression database with 200+ tables and complex objects."""
from pathlib import Path
out=Path(__file__).with_name('GoldenMigrationDB.sql')
L=["IF DB_ID('GoldenMigrationDB') IS NULL CREATE DATABASE GoldenMigrationDB;","GO","USE GoldenMigrationDB;","GO","IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name='core') EXEC('CREATE SCHEMA core');","IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name='reporting') EXEC('CREATE SCHEMA reporting');","GO"]
for i in range(1,201):
    L += [f"CREATE TABLE core.Entity{i:03d}(Id INT IDENTITY PRIMARY KEY, ParentId INT NULL, Code NVARCHAR(50) NOT NULL, Amount DECIMAL(18,4) NULL, PayloadXml XML NULL, JsonText NVARCHAR(MAX) NULL, CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(), RV ROWVERSION, ComputedAmount AS (ISNULL(Amount,0)*1.1), CONSTRAINT CK_Entity{i:03d}_Amount CHECK (Amount IS NULL OR Amount>=0));","GO"]
for i in range(2,201): L += [f"ALTER TABLE core.Entity{i:03d} ADD CONSTRAINT FK_Entity{i:03d}_Prev FOREIGN KEY(ParentId) REFERENCES core.Entity{i-1:03d}(Id);","CREATE INDEX IX_Entity%03d_Code ON core.Entity%03d(Code) INCLUDE(Amount,CreatedAt);"%(i,i),"GO"]
for i in range(1,31): L += [f"CREATE VIEW reporting.vw_Aggregate{i:02d} AS SELECT Code, COUNT_BIG(*) RowCount, SUM(Amount) TotalAmount FROM core.Entity{i:03d} GROUP BY Code;","GO"]
for i in range(1,21): L += [f"CREATE PROCEDURE core.usp_Load{i:02d} @MinId INT=0 AS BEGIN SET NOCOUNT ON; BEGIN TRY; CREATE TABLE #x(Id INT); INSERT #x SELECT Id FROM core.Entity{i:03d} WHERE Id>@MinId; MERGE core.Entity{i+1:03d} T USING #x S ON T.Id=S.Id WHEN MATCHED THEN UPDATE SET Code=CONCAT('U',S.Id) WHEN NOT MATCHED THEN INSERT(Code) VALUES(CONCAT('N',S.Id)); END TRY BEGIN CATCH THROW; END CATCH; END;","GO"]
for i in range(1,16): L += [f"CREATE FUNCTION core.fn_Value{i:02d}(@v DECIMAL(18,4)) RETURNS DECIMAL(18,4) AS BEGIN RETURN ISNULL(@v,0)*{i}; END;","GO"]
for i in range(1,11): L += [f"CREATE TRIGGER core.tr_Audit{i:02d} ON core.Entity{i:03d} AFTER INSERT,UPDATE AS BEGIN SET NOCOUNT ON; SELECT COUNT(*) AS ChangedRows FROM inserted; END;","GO"]
L += ["-- Dynamic SQL, cursor, recursive CTE and cross-schema examples", "CREATE PROCEDURE core.usp_Complex AS BEGIN DECLARE @sql nvarchar(max)=N'SELECT TOP 10 * FROM core.Entity001'; EXEC sp_executesql @sql; DECLARE c CURSOR LOCAL FAST_FORWARD FOR SELECT Id FROM core.Entity002; OPEN c; DECLARE @i int; FETCH NEXT FROM c INTO @i; WHILE @@FETCH_STATUS=0 BEGIN FETCH NEXT FROM c INTO @i; END; CLOSE c; DEALLOCATE c; END;","GO","WITH R AS (SELECT Id,ParentId,0 Lvl FROM core.Entity010 WHERE ParentId IS NULL UNION ALL SELECT E.Id,E.ParentId,R.Lvl+1 FROM core.Entity010 E JOIN R ON E.ParentId=R.Id) SELECT * FROM R OPTION(MAXRECURSION 100);","GO"]
out.write_text('\n'.join(L),encoding='utf-8');print(out)
